spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://act.postgres.uhserver.com:5432/act
    username: rltiact
    password: Dev@8524*
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true